### ISSUE TITLE
Great Job :muscle: 

### ISSUE THREAD

**Issue by nachosala89** [vicmaburrito/Awesome_Books#5]
You made a great job so far! However, I will let you some suggestions in the comments that you can consider to improve your project.

**Comment by nachosala89** [comment]
You use the type="submit" for your add button. Since you don't communicate with the backend, I think it would be better if you use type="button", so the page don't reload every time you click it.

**Comment by vicmaburrito** [comment]
> You use the type="submit" for your add button. Since you don't communicate with the backend, I think it would be better if you use type="button", so the page don't reload every time you click it.

Thank you very much for the feedback! I will implement your recommendation! @nachosala89
